// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdshkN4CGosstbZrkSLpvcuHqPMEQZ2rg',
    appId: '1:620468509216:web:262a2ba59fedaf306afa45',
    messagingSenderId: '620468509216',
    projectId: 'sushiman-app-4f03c',
    authDomain: 'sushiman-app-4f03c.firebaseapp.com',
    storageBucket: 'sushiman-app-4f03c.appspot.com',
    measurementId: 'G-B1DT78F553',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPIq_CCqwmNOfVSBOgg5D1jIxyB8_Iyg',
    appId: '1:620468509216:android:191f0ccfb40760726afa45',
    messagingSenderId: '620468509216',
    projectId: 'sushiman-app-4f03c',
    storageBucket: 'sushiman-app-4f03c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq5bha_PRMbXaylry5JqulQKaK_67f4MQ',
    appId: '1:620468509216:ios:bcc24a2d00689a446afa45',
    messagingSenderId: '620468509216',
    projectId: 'sushiman-app-4f03c',
    storageBucket: 'sushiman-app-4f03c.appspot.com',
    iosBundleId: 'com.example.sushiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq5bha_PRMbXaylry5JqulQKaK_67f4MQ',
    appId: '1:620468509216:ios:bcc24a2d00689a446afa45',
    messagingSenderId: '620468509216',
    projectId: 'sushiman-app-4f03c',
    storageBucket: 'sushiman-app-4f03c.appspot.com',
    iosBundleId: 'com.example.sushiApp',
  );
}
